# Copyright (c) 2019-2022, The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

jobs:
  - job: check_codespell
    displayName: "codespell"
    pool:
      vmImage: "ubuntu-latest"
    container: khronosgroup/docker-images:openxr-sdk.202110
    steps:
      - script: ./checkCodespell
        displayName: Run Codespell script
