// Copyright (c) 2020-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: Apache-2.0

// Open this directory in Android Studio, or build with Gradle,
// to build the conformance suite.

plugins {
    id 'com.android.application' version '8.1.4'
}


// These next few lines are just to make the version match the OpenXR release.
project.ext.repoRoot = file('../../')
apply from: file('../version.gradle')

def assetDest = layout.buildDir.dir('intermediates/assets')

tasks.register('copyAssets', Copy) {
    // fonts
    from('conformance_test') {
        include '*.otf'
    }

    // immersive images
    from('conformance_test/composition_assets') {
        include '*.png'
    }

    // sample images
    from('conformance_test/composition_examples') {
        include '*.png'
        include '*.jpg'
    }
    from('conformance_test/gltf_examples') {
        include '*.png'
        include '*.glb'
    }
    from('conformance_test/pbr_assets') {
        include '*.png'
    }

    // layer manifests
    from('conformance_test/android_assets') {
        include '**/*.json'
    }

    into assetDest
}

android {
    compileSdk 34
    ndkVersion "23.2.8568313"
    buildToolsVersion = "34.0.0"
    namespace 'org.khronos.openxr.cts'

    defaultConfig {
        applicationId "org.khronos.openxr.cts"
        // for Vulkan, need at least 24
        minSdkVersion 24
        targetSdkVersion 34

        versionName = project.versionOpenXR.toString() + project.versionQualifier
        versionCode = project.versionOpenXR.getVersionCode()

        externalNativeBuild {
            cmake {
                arguments '-DBUILD_TESTS=OFF',
                        '-DBUILD_LOADER=ON',
                        '-DBUILD_CONFORMANCE_TESTS=ON',
                        '-DBUILD_ALL_EXTENSIONS=ON'
                targets 'conformance_test', 'openxr_loader', 'XrApiLayer_runtime_conformance'
            }
        }
        preBuild.dependsOn(copyAssets)
    }
    sourceSets {
        main {
            manifest.srcFile 'platform_specific/AndroidManifest.xml'
            res.srcDirs 'platform_specific/android_resources'
            assets.srcDirs assetDest
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path "${project.repoRoot}/CMakeLists.txt"
        }
    }
}

// Fix error about undeclared deps when building as release with
// gradle 8+.
afterEvaluate {
    android.applicationVariants.all { def variant ->
        def targetName = variant.name.capitalize()

        // This one is needed by command line builds
        def mergeAssetsTask = tasks.findByName("merge${targetName}Assets")
        mergeAssetsTask.dependsOn(copyAssets)

        // These only show up when building with Android Studio, hence the conditionals
        def mergeTestAssetsTask = tasks.findByName("merge${targetName}AndroidTestAssets")
        if (mergeTestAssetsTask) {
            mergeAssetsTask.dependsOn(mergeTestAssetsTask)
        }

        def lintVitalAnalyzeTask = tasks.findByName("lintVitalAnalyze${targetName}")
        if (lintVitalAnalyzeTask) {
            lintVitalAnalyzeTask.dependsOn(mergeAssetsTask)
        }
    }
}
