// Copyright (c) 2019-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[selftests]]
== Interactive Self Tests

Some interactive tests are primarily a test of mechanisms within the CTS,
rather than runtime functionality.
These are labeled with the tag `[self_test]` rather than `[scenario]`,
`[actions]`, or `[composition]`.
While it is good to run these, and doing so may help troubleshoot failures
with tests that build on them, submission of a CTS results package does not
require them.
Currently, the only self-tests tagged in this way are for the PBR/glTF
rendering subsystem.
They (asynchronously) load very large, artificial test assets, originally
from the "glTF-Sample-Models" repository, to test specific details of the
renderer.

To run the self-tests, commands similar to the following can be used:

.Example command lines
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.

[source,sh]
----
conformance_cli "[self_test][interactive]" -G d3d11 --reporter ctsxml::out=interactive_self_test_d3d11.xml --reporter console
conformance_cli "[self_test][interactive]" -G d3d12 --reporter ctsxml::out=interactive_self_test_d3d12.xml --reporter console
conformance_cli "[self_test][interactive]" -G vulkan --reporter ctsxml::out=interactive_self_test_vulkan.xml --reporter console
conformance_cli "[self_test][interactive]" -G vulkan2 --reporter ctsxml::out=interactive_self_test_vulkan2.xml --reporter console
conformance_cli "[self_test][interactive]" -G opengl --reporter ctsxml::out=interactive_self_test_opengl.xml --reporter console
----
====

.Corresponding ADB commands to launch on Android
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[self_test][interactive]" -e graphicsPlugin vulkan -e xmlFilename interactive_self_test_vulkan.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_self_test_vulkan.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[self_test][interactive]" -e graphicsPlugin vulkan2 -e xmlFilename interactive_self_test_vulkan2.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_self_test_vulkan2.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[self_test][interactive]" -e graphicsPlugin opengles -e xmlFilename interactive_self_test_opengles.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_self_test_opengles.xml

----
====
