// Copyright (c) 2019-2026 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[submissions-criteria]]
== Passing Criteria

A conformance run is considered passing if **all tests** required by the
testing steps finish with allowed result codes (pass or skip as
appropriate), and all warnings are acceptably explained to describe why they
are not a conformance failure.
`XR_EXT_conformance_automation` **must** not be used for conformance
submission.


[IMPORTANT]
====
Any error or failure when testing functionality means your runtime is **not
conformant**.

Any warnings **may** indicate non-conformance and **must** be explained in
the submission package.
====


Test results are contained in the output XML files, which are an extension
of the common "*Unit" schema with some custom elements.
Each test case leaf section is reached by a run of its own, and is recorded
with a `testcase` tag, e.g.:

[source,xml]
----
<testcase classname="global" name="Swapchains/Swapchain creation test parameters" time="1.207" cts:tags="[composition]" status="run">
----

If all assertions in that case passed, there are no child elements to the
`testcase` tag.
However, `testcase` tags can contain a warning, failure, or error:

[source,xml]
----
<cts:warning type="WARN">
----

or

[source,xml]
----
<failure message="..." type="...">
----

or

[source,xml]
----
<error message="..." type="...">
----

With the results of the entire run summarized in `testsuite` tag (listing
the number of assertions):

[source,xml]
----
<testsuite errors="0" failures="0" tests="<number of successful assertions>" time="1.407">
----

as well as in the `cts:results` tag in `cts:ctsConformanceReport` (listing
the number of top level test cases):

[source,xml]
----
<cts:results testSuccessCount="1" testFailureCount="0"/>
----

The `cts:ctsTestEnvironment` block also records runtime capability data used
to interpret the submission independently of the tester-selected command-line
options. In addition to available API layers and instance extensions, it may
contain the form factors for which the runtime returned a system, the view
configurations available for each system, and the environment blend modes
available for each view configuration:

[source,xml]
----
<cts:availableFormFactors>
  <cts:formFactor value="XR_FORM_FACTOR_HEAD_MOUNTED_DISPLAY">
    <cts:availableViewConfigurations>
      <cts:viewConfiguration value="XR_VIEW_CONFIGURATION_TYPE_PRIMARY_STEREO">
        <cts:availableEnvironmentBlendModes>
          <cts:environmentBlendMode value="XR_ENVIRONMENT_BLEND_MODE_OPAQUE"/>
        </cts:availableEnvironmentBlendModes>
      </cts:viewConfiguration>
    </cts:availableViewConfigurations>
  </cts:formFactor>
</cts:availableFormFactors>
----
