// Copyright (c) 2019-2024, The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[submissions-testing-steps]]
== Testing steps

The tests are marked with tags to accomplish several objectives.

* selecting a subset of tests to run with different arguments (graphics API,
  preferred interaction profile, API version) to ensure maximum coverage
  when running the CTS to make a conformance submission.
* selecting a related subset of tests to use as an aid during runtime
  development.
* selecting those tests that may be run in a scheduled or continuous testing
  setup for runtime quality assurance.

The following text lays out the steps to running conformance for submission.

Note: If you do not supply the `--apiVersion` argument, it defaults to the
latest OpenXR version as defined in the CTS's own OpenXR header.
When running the CTS for a conformance submission, you should **always**
supply an `--apiVersion` argument.

Please be aware that depending on how you view these instructions, the (very
long) sample command lines **may** be wrapped automatically.
All the desktop command lines start with `conformance_cli`, while all the
Android ones start with `adb shell am`.

=== Automated tests: each supported graphics API and each OpenXR API version

One run and result file for each element of the Cartesian product of the
following dimensions:

* Each graphics API
** While not all automated tests interact with the graphics API, many do,
   and all these tests **must** be able to pass with every supported
   graphics API.
* Each OpenXR API version
** For now, these **must** be run for both OpenXR 1.0 and 1.1 when
   submitting results for 1.1.
   Running as 1.0 on a 1.1 runtime selects assertions to verify that no 1.1
   behavior is exposed to applications requesting 1.0.


When using the following examples, omit any graphics API binding extensions
your runtime does not support.

.Example command lines for OpenXR 1.0
[%collapsible]
====

[source,sh]
----
conformance_cli "exclude:[interactive]" -G d3d11 --apiVersion 1.0 --reporter ctsxml::out=automated_d3d11_1_0.xml

conformance_cli "exclude:[interactive]" -G d3d12 --apiVersion 1.0 --reporter ctsxml::out=automated_d3d12_1_0.xml

conformance_cli "exclude:[interactive]" -G vulkan --apiVersion 1.0 --reporter ctsxml::out=automated_vulkan_1_0.xml

conformance_cli "exclude:[interactive]" -G vulkan2 --apiVersion 1.0 --reporter ctsxml::out=automated_vulkan2_1_0.xml

conformance_cli "exclude:[interactive]" -G opengl --apiVersion 1.0 --reporter ctsxml::out=automated_opengl_1_0.xml

conformance_cli "exclude:[interactive]" -G metal --apiVersion 1.0 --reporter ctsxml::out=automated_metal_1_0.xml

----
====

.Example command lines for OpenXR 1.1
[%collapsible]
====

[source,sh]
----
conformance_cli "exclude:[interactive]" -G d3d11 --apiVersion 1.1 --reporter ctsxml::out=automated_d3d11_1_1.xml

conformance_cli "exclude:[interactive]" -G d3d12 --apiVersion 1.1 --reporter ctsxml::out=automated_d3d12_1_1.xml

conformance_cli "exclude:[interactive]" -G vulkan --apiVersion 1.1 --reporter ctsxml::out=automated_vulkan_1_1.xml

conformance_cli "exclude:[interactive]" -G vulkan2 --apiVersion 1.1 --reporter ctsxml::out=automated_vulkan2_1_1.xml

conformance_cli "exclude:[interactive]" -G opengl --apiVersion 1.1 --reporter ctsxml::out=automated_opengl_1_1.xml

conformance_cli "exclude:[interactive]" -G metal --apiVersion 1.1 --reporter ctsxml::out=automated_metal_1_1.xml
----
====


.Corresponding ADB commands to launch on Android for OpenXR 1.0
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan -e apiVersion 1.0 -e xmlFilename automated_vulkan_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan_1_0.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan2 -e apiVersion 1.0 -e xmlFilename automated_vulkan2_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan2_1_0.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin opengles -e apiVersion 1.0 -e xmlFilename automated_opengles_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_opengles_1_0.xml

----
====

.Corresponding ADB commands to launch on Android for OpenXR 1.1
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan -e apiVersion 1.1 -e xmlFilename automated_vulkan_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan_1_1.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan2 -e apiVersion 1.1 -e xmlFilename automated_vulkan2_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan2_1_1.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin opengles -e apiVersion 1.1 -e xmlFilename automated_opengles_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_opengles_1_1.xml

----
====

=== Interactive composition tests on each supported graphics API and each OpenXR API version

These are separate as a tester **must** evaluate the results and determine
if each test is passed or failed.

These tests use the `khr/simple_controller` interaction profile to review
instructions and sample output, as well as to indicate pass or fail.

One run and result file for the each element of the Cartesian product of the
following dimensions:

* Each graphics API
* Each OpenXR API version?
** Composition behavior is unchanged in 1.1, but if there is a chance
   behavior may differ between 1.0 and 1.1 applications, the tests should be
   run under both versions.

As previously, when using these examples, omit any graphics API binding
extensions your runtime does not support.

.Example command lines for OpenXR 1.0
[%collapsible]
====

[source,sh]
----
conformance_cli "[composition][interactive]" -G d3d11 --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_d3d11_1_0.xml

conformance_cli "[composition][interactive]" -G d3d12 --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_d3d12_1_0.xml

conformance_cli "[composition][interactive]" -G vulkan --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_vulkan_1_0.xml

conformance_cli "[composition][interactive]" -G vulkan2 --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_vulkan2_1_0.xml

conformance_cli "[composition][interactive]" -G opengl --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_opengl_1_0.xml

conformance_cli "[composition][interactive]" -G metal --apiVersion 1.0 --reporter ctsxml::out=interactive_composition_metal_1_0.xml

----
====

.Example command lines for OpenXR 1.1
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.

[source,sh]
----
conformance_cli "[composition][interactive]" -G d3d11 --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_d3d11_1_1.xml

conformance_cli "[composition][interactive]" -G d3d12 --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_d3d12_1_1.xml

conformance_cli "[composition][interactive]" -G vulkan --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_vulkan_1_1.xml

conformance_cli "[composition][interactive]" -G vulkan2 --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_vulkan2_1_1.xml

conformance_cli "[composition][interactive]" -G opengl --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_opengl_1_1.xml

conformance_cli "[composition][interactive]" -G metal --apiVersion 1.1 --reporter ctsxml::out=interactive_composition_metal_1_1.xml

----
====


.Corresponding ADB commands to launch on Android for OpenXR 1.0
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan -e apiVersion 1.0 -e xmlFilename interactive_composition_vulkan_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan_1_0.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan2 -e apiVersion 1.0 -e xmlFilename interactive_composition_vulkan2_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan2_1_0.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin opengles -e apiVersion 1.0 -e xmlFilename interactive_composition_opengles_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_opengles_1_0.xml

----
====

.Corresponding ADB commands to launch on Android for OpenXR 1.1
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan -e apiVersion 1.1 -e xmlFilename interactive_composition_vulkan_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan_1_1.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan2 -e apiVersion 1.1 -e xmlFilename interactive_composition_vulkan2_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan2_1_1.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin opengles -e apiVersion 1.1 -e xmlFilename interactive_composition_opengles_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_opengles_1_1.xml

----
====

=== Interactive scenario tests, for at least one graphics API

These tests focus on interactive behavior of the runtime and are generally
undemanding on the graphics API.
While they should be possible to pass on all graphics APIs, a conformance
submission only requires a report showing an overall pass on a single API.

These tests use the `khr/simple_controller` interaction profile to perform
actions and indicate pass or fail.

* One graphics API
* Each OpenXR API version?


.Example command lines for OpenXR 1.0
[%collapsible]
====
[source,sh]
----
conformance_cli "[scenario][interactive]" -G opengl --apiVersion 1.0 --reporter ctsxml::out=interactive_scenarios_1_0.xml

----
====

.Example command lines for OpenXR 1.1
[%collapsible]
====
[source,sh]
----
conformance_cli "[scenario][interactive]" -G opengl --apiVersion 1.1 --reporter ctsxml::out=interactive_scenarios_1_1.xml

----
====


.Corresponding ADB commands to launch on Android for OpenXR 1.0
[%collapsible]
====
[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[scenario][interactive]" -e apiVersion 1.0 -e xmlFilename interactive_scenarios_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_scenarios_1_0.xml
----
====

.Corresponding ADB commands to launch on Android for OpenXR 1.1
[%collapsible]
====
[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[scenario][interactive]" -e apiVersion 1.1 -e xmlFilename interactive_scenarios_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_scenarios_1_1.xml
----
====

=== Interactive action tests, for each generic interaction profile you can bind completely, and each interaction profile whose concrete device/method is supported by your runtime.

These tests are selected with `[actions][interactive]`.
Pass the interaction profile to test, without the leading
`/interaction_profile/`, with the option `-I`

* One graphics API
* Each OpenXR API version
** If extensions are required for a specified interaction profile to be
   available, the CTS will automatically enable them for the entire test
   run.
* Each interaction profile that is either:
** A generic interaction profile (such as `khr/simple_controller`) for which
   all inputs can be activated.
** The interaction profile with which the device/input method is most
   closely associated.
*** If more than one interaction profile is closely associated with the
    device/method, e.g in the case of evolutionary upgrades to controllers,
    it is recommended to run specifying each of those interaction profiles.

One of these tests requires being able to activate all inputs specified (and
not marked as "system") for an interaction profile.

For any supported interaction profiles that are valid for `/user/gamepad`
rather than `/user/hand/left` and `/user/hand/right`, further filter the
tests by specifying the tag `[gamepad]`.


.Example command lines for OpenXR 1.0
[%collapsible]
====
Select the interaction profiles to test based on the preceding description.

[source,sh]
----
# Generic profile
conformance_cli "[actions][interactive]" -G d3d11 -I "khr/simple_controller" --apiVersion 1.0 --reporter ctsxml::out=interactive_action_simple_controller_1_0.xml


# Sample device-associated profiles
conformance_cli "[actions][interactive]" -G d3d11 -I "microsoft/motion_controller" --apiVersion 1.0 --reporter ctsxml::out=interactive_action_microsoft_motion_controller_1_0.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "oculus/touch_controller" --apiVersion 1.0 --reporter ctsxml::out=interactive_action_oculus_touch_controller_1_0.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "htc/vive_controller" --apiVersion 1.0 --reporter ctsxml::out=interactive_action_htc_vive_controller_1_0.xml

----
====

.Example command lines for OpenXR 1.1
[%collapsible]
====
Select the interaction profiles to test based on the preceding description.
[source,sh]
----
# Generic profile
conformance_cli "[actions][interactive]" -G d3d11 -I "khr/simple_controller" --apiVersion 1.1 --reporter ctsxml::out=interactive_action_simple_controller_1_1.xml


# Sample device-associated profiles
conformance_cli "[actions][interactive]" -G d3d11 -I "microsoft/motion_controller" --apiVersion 1.1 --reporter ctsxml::out=interactive_action_microsoft_motion_controller_1_1.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "oculus/touch_controller" --apiVersion 1.1 --reporter ctsxml::out=interactive_action_oculus_touch_controller_1_1.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "htc/vive_controller" --apiVersion 1.1 --reporter ctsxml::out=interactive_action_htc_vive_controller_1_1.xml

----
====


.Example command lines for a gamepad on OpenXR 1.0
[%collapsible]
====
[source,sh]
----
conformance_cli "[gamepad]" -G d3d11 -I "microsoft/xbox_controller" --apiVersion 1.0 --reporter ctsxml::out=interactive_action_microsoft_xbox_controller_1_0.xml
----
====

.Example command lines for a gamepad on OpenXR 1.1
[%collapsible]
====
[source,sh]
----
conformance_cli "[gamepad]" -G d3d11 -I "microsoft/xbox_controller" --apiVersion 1.1 --reporter ctsxml::out=interactive_action_microsoft_xbox_controller_1_1.xml
----
====


.Corresponding ADB commands to launch on Android for OpenXR 1.0
[%collapsible]
====
Select the interaction profiles to test based on the preceding description.

[source,sh]
----
## Generic profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,khr/simple_controller" -e apiVersion 1.0 -e xmlFilename interactive_action_simple_controller_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_simple_controller_1_0.xml


## Sample device-associated profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,oculus/touch_controller" -e apiVersion 1.0 -e xmlFilename interactive_action_oculus_touch_controller_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_oculus_touch_controller_1_0.xml


## Sample gamepad profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[gamepad],-I,microsoft/xbox_controller" -e apiVersion 1.0 -e xmlFilename interactive_action_microsoft_xbox_controller_1_0.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_microsoft_xbox_controller_1_0.xml

----
====

.Corresponding ADB commands to launch on Android for OpenXR 1.1
[%collapsible]
====
[source,sh]
----
## Generic profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,khr/simple_controller" -e apiVersion 1.1 -e xmlFilename interactive_action_simple_controller_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_simple_controller_1_1.xml


## Sample device-associated profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,oculus/touch_controller" -e apiVersion 1.1 -e xmlFilename interactive_action_oculus_touch_controller_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_oculus_touch_controller_1_1.xml


## Sample gamepad profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[gamepad],-I,microsoft/xbox_controller" -e apiVersion 1.1 -e xmlFilename interactive_action_microsoft_xbox_controller_1_1.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_microsoft_xbox_controller_1_1.xml

----
====
