// Copyright (c) 2019-2025 The Khronos Group Inc.
//
// SPDX-License-Identifier: CC-BY-4.0

[[submissions-testing-steps]]
== Testing steps

The tests are marked with tags to accomplish several objectives.

* selecting a subset of tests to run with different arguments (graphics API,
  preferred interaction profile, API version) to ensure maximum coverage
  when running the CTS to make a conformance submission.
* selecting a related subset of tests to use as an aid during runtime
  development.
* selecting those tests that may be run in a scheduled or continuous testing
  setup for runtime quality assurance.

The following text lays out the steps to running conformance for submission.

Note: If you do not support OpenXR 1.0, you must supply the `--minApiVersion`
argument to specify the lowest OpenXR API version you support, e.g.
`--minApiVersion 1.1`. Some tests will automatically test behaviour on higher
API versions if your runtime supports them, but most tests will run on
`minApiVersion`, which defaults to `1.0`.

Please be aware that depending on how you view these instructions, the (very
long) sample command lines **may** be wrapped automatically.
All the desktop command lines start with `conformance_cli`, while all the
Android ones start with `adb shell am`.

=== Automated tests on each supported graphics API

One run and result file for the each graphics API supported by your runtime.

When using the following examples, omit any graphics API binding extensions
your runtime does not support.

.Example command lines
[%collapsible]
====

[source,sh]
----
conformance_cli "exclude:[interactive]" -G d3d11 --reporter ctsxml::out=automated_d3d11.xml

conformance_cli "exclude:[interactive]" -G d3d12 --reporter ctsxml::out=automated_d3d12.xml

conformance_cli "exclude:[interactive]" -G vulkan --reporter ctsxml::out=automated_vulkan.xml

conformance_cli "exclude:[interactive]" -G vulkan2 --reporter ctsxml::out=automated_vulkan2.xml

conformance_cli "exclude:[interactive]" -G opengl --reporter ctsxml::out=automated_opengl.xml

conformance_cli "exclude:[interactive]" -G metal --reporter ctsxml::out=automated_metal.xml

----
====


.Corresponding ADB commands to launch on Android
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan -e xmlFilename automated_vulkan.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin vulkan2 -e xmlFilename automated_vulkan2.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_vulkan2.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "exclude:[interactive]" -e graphicsPlugin opengles -e xmlFilename automated_opengles.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/automated_opengles.xml

----
====

=== Interactive composition tests on each supported graphics API

These are separate as a tester **must** evaluate the results and determine
if each test is passed or failed.

These tests use the `khr/simple_controller` interaction profile to review
instructions and sample output, as well as to indicate pass or fail.

One run and result file for the each graphics API supported by your runtime.

As previously, when using these examples, omit any graphics API binding
extensions your runtime does not support.

.Example command lines
[%collapsible]
====

[source,sh]
----
conformance_cli "[composition][interactive]" -G d3d11 --reporter ctsxml::out=interactive_composition_d3d11.xml

conformance_cli "[composition][interactive]" -G d3d12 --reporter ctsxml::out=interactive_composition_d3d12.xml

conformance_cli "[composition][interactive]" -G vulkan --reporter ctsxml::out=interactive_composition_vulkan.xml

conformance_cli "[composition][interactive]" -G vulkan2 --reporter ctsxml::out=interactive_composition_vulkan2.xml

conformance_cli "[composition][interactive]" -G opengl --reporter ctsxml::out=interactive_composition_opengl.xml

conformance_cli "[composition][interactive]" -G metal --reporter ctsxml::out=interactive_composition_metal.xml

----
====


.Corresponding ADB commands to launch on Android
[%collapsible]
====
Omit any graphics API binding extensions your runtime does not support.
These commands do not match one-to-one with the desktop examples due to
different graphics API availability on Android.

[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan -e xmlFilename interactive_composition_vulkan.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin vulkan2 -e xmlFilename interactive_composition_vulkan2.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_vulkan2.xml


adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[composition][interactive]" -e graphicsPlugin opengles -e xmlFilename interactive_composition_opengles.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_composition_opengles.xml

----
====

=== Interactive scenario tests, for at least one graphics API

These tests focus on interactive behavior of the runtime and are generally
undemanding on the graphics API.
While they should be possible to pass on all graphics APIs, a conformance
submission only requires a report showing an overall pass on a single API.

These tests use the `khr/simple_controller` interaction profile to perform
actions and indicate pass or fail.

* One graphics API


.Example command lines
[%collapsible]
====
[source,sh]
----
conformance_cli "[scenario][interactive]" -G opengl --reporter ctsxml::out=interactive_scenarios.xml

----
====


.Corresponding ADB commands to launch on Android
[%collapsible]
====
[source,sh]
----
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[scenario][interactive]" -e xmlFilename interactive_scenarios.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_scenarios.xml
----
====

=== Interactive action tests, for each generic interaction profile you can bind completely, and each interaction profile whose concrete device/method is supported by your runtime.

These tests are selected with `[actions][interactive]`.
Pass the interaction profile to test, without the leading
`/interaction_profile/`, with the option `-I`

* One graphics API
* Each OpenXR API version
** If extensions are required for a specified interaction profile to be
   available, the CTS will automatically enable them for the entire test
   run.
* Each interaction profile that is either:
** A generic interaction profile (such as `khr/simple_controller`) for which
   all inputs can be activated.
** The interaction profile with which the device/input method is most
   closely associated.
*** If more than one interaction profile is closely associated with the
    device/method, e.g in the case of evolutionary upgrades to controllers,
    it is recommended to run specifying each of those interaction profiles.

One of these tests requires being able to activate all inputs specified (and
not marked as "system") for an interaction profile.

For any supported interaction profiles that are valid for `/user/gamepad`
rather than `/user/hand/left` and `/user/hand/right`, further filter the
tests by specifying the tag `[gamepad]`.

To clarify, if you support providing input for all components of one of the
following interaction profiles, specify them as well.

* `/interaction_profiles/khr/simple_controller`
* `/interaction_profiles/ext/hand_interaction_ext`
* `/interaction_profiles/ext/eye_gaze_interaction`

.Example command lines
[%collapsible]
====
Select the interaction profiles to test based on the preceding description.

[source,sh]
----
## Generic: Simple controller
conformance_cli "[actions][interactive]" -G d3d11 -I "khr/simple_controller" --reporter ctsxml::out=interactive_action_simple_controller.xml

## Generic: Hand interaction (whether via hand tracking or controller)
conformance_cli "[actions][interactive]" -G d3d11 -I "ext/hand_interaction_ext" --reporter ctsxml::out=interactive_action_ext_hand_interaction_interaction.xml

## Generic: Eye gaze
conformance_cli "[actions][interactive]" -G d3d11 -I "ext/eye_gaze_interaction" --reporter ctsxml::out=interactive_action_ext_eye_gaze_interaction.xml

# Sample device-associated profiles
conformance_cli "[actions][interactive]" -G d3d11 -I "microsoft/motion_controller" --reporter ctsxml::out=interactive_action_microsoft_motion_controller.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "oculus/touch_controller" --reporter ctsxml::out=interactive_action_oculus_touch_controller.xml

conformance_cli "[actions][interactive]" -G d3d11 -I "htc/vive_controller" --reporter ctsxml::out=interactive_action_htc_vive_controller.xml

----
====


.Example command lines for a gamepad
[%collapsible]
====
[source,sh]
----
conformance_cli "[gamepad]" -G d3d11 -I "microsoft/xbox_controller" --reporter ctsxml::out=interactive_action_microsoft_xbox_controller.xml
----
====


.Corresponding ADB commands to launch on Android
[%collapsible]
====
Select the interaction profiles to test based on the preceding description.

[source,sh]
----
## Generic: Simple controller
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,khr/simple_controller" -e xmlFilename interactive_action_simple_controller.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_simple_controller.xml


## Generic: Hand interaction (whether via hand tracking or controller)
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,ext/hand_interaction_ext" -e xmlFilename interactive_action_ext_hand_interaction.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_ext_hand_interaction.xml


## Generic: Eye gaze interaction
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,ext/eye_gaze_interaction" -e xmlFilename interactive_action_ext_eye_gaze_interaction.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_ext_eye_gaze_interaction.xml


## Sample device-associated profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[actions][interactive],-I,oculus/touch_controller" -e xmlFilename interactive_action_oculus_touch_controller.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_oculus_touch_controller.xml


## Sample gamepad profile
adb shell am start-activity -S -n org.khronos.openxr.cts/android.app.NativeActivity --esa args "[gamepad],-I,microsoft/xbox_controller" -e xmlFilename interactive_action_microsoft_xbox_controller.xml

# Wait until tests complete, then retrieve results with
adb pull /sdcard/Android/data/org.khronos.openxr.cts/files/interactive_action_microsoft_xbox_controller.xml

----
====
