# Copyright (c) 2020-2021 The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0
jobs:
- job: check_file_format
  displayName: 'Check file formatting'
  pool:
    vmImage: 'ubuntu-20.04'
  container: khronosgroup/docker-images:openxr-sdk
  steps:
    - script: apt-get install -qq dos2unix recode
      displayName: Install dependencies
    - script: ./file_format.sh
      displayName: File formatting checks (file_format.sh)

    - script: git diff --patch --exit-code > file_format.patch
      displayName: Save changes as diff
    - script: echo "The following files need file formatting:"; sed -n -e "s/^diff.* b\///p" file_format.patch
      condition: failed()
    - task: PublishPipelineArtifact@1
      displayName: Publish diff
      condition: failed()
      inputs:
        path: $(System.DefaultWorkingDirectory)/file_format.patch
        artifact: file_format_changes
