# Copyright (c) 2019-2022, The Khronos Group Inc.
# SPDX-License-Identifier: Apache-2.0

# Main azure-pipelines configuration for the OpenXR-CTS repo.
trigger:
  branches:
    include:
      - "*"
variables:
  VULKAN_SDK_VERSION: "1.1.114.0"

stages:
  - stage: Check
    jobs:
      - template: shared/check_clang_format.yml
      # - template: shared/check_file_format.yml

  - stage: Build
    jobs:
      - template: shared/build_jobs.yml
        parameters:
          isSdkSourceRepo: false
