# Copyright 2021-2024, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android OpenXR-CTS - Android Build
on:
  workflow_call:
    inputs:
      gradleTask:
        description: "Gradle task to run"
        type: string
        required: true
      gradleOutputDir:
        description: "Where do we look for the output?"
        type: string
        required: true

jobs:
  # CTS
  build-android-cts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-tags: "${{ inputs.gradleTask != 'assembleRelease' }}"
          fetch-depth: "${{ github.event.release && '0' || '1'}}"

      - name: Get modern CMake and Ninja
        uses: lukka/get-cmake@v3.30.5

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      # Also performs Gradle wrapper validation
      - uses: "gradle/actions/setup-gradle@v4"

      - name: "Build with Gradle"
        run: "cd src/conformance && ./gradlew ${{ inputs.gradleTask }}"

      - name: Upload unsigned artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-openxr-cts-unsigned
          path: ${{ inputs.gradleOutputDir }}
