# Copyright 2021-2024, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android OpenXR-CTS
on:
  pull_request:
    branches:
      - "devel"
  push:
    branches:
      - "devel"

jobs:
  build-cts-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get modern CMake and Ninja
        uses: lukka/get-cmake@v3.30.3

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      # Also performs Gradle wrapper validation
      - uses: "gradle/actions/setup-gradle@v4"

      - name: "Build with Gradle"
        run: "cd src/conformance && ./gradlew assembleDebug"

      - name: Upload OpenXR-CTS Android
        uses: actions/upload-artifact@v4
        with:
          name: OpenXR-CTS Android
          path: src/conformance/build/outputs/apk/debug/conformance-debug.apk
