# Copyright 2021-2023, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Android OpenXR-CTS
on:
  pull_request:
    branches:
      - "devel"
  push:
    branches:
      - "devel"

jobs:
  build-loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Get modern CMake and Ninja
        uses: lukka/get-cmake@v3.27.7

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: gradle

      - uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: assembleDebug
          build-root-directory: src/conformance

      - name: Upload OpenXR-CTS Android
        uses: actions/upload-artifact@v3
        with:
          name: OpenXR-CTS Android
          path: src/conformance/build/outputs/apk/debug/conformance-debug.apk
