# Copyright 2022, Collabora, Ltd.
# SPDX-License-Identifier: CC0-1.0

name: Validate Gradle Wrapper

on:
  push:
    branches: [ devel ]

  pull_request:
    branches: [ devel ]

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
